/*
 * base.h
 *
 *  Created on: Jul 3, 2025
 *      Author: Harrish Manoj
 */

#ifndef INC_BASE_H_
#define INC_BASE_H_

#include<stdbool.h>

//PERIPHERAL BASE
#define PERIPHERAL_BASE                 (0x40000000UL)


//SECTION APB1
#define APB1_PERIPHERAL_OFFSET			(0x0000UL)
#define APB1_PERIPHERAL					(PERIPHERAL_BASE + APB1_PERIPHERAL_OFFSET)

#define I2C1_PERIPHERAL_OFFSET			(0x00005400UL)
#define I2C1_PERIPHERAL					(APB1_PERIPHERAL + I2C1_PERIPHERAL_OFFSET)

#define USART2_PERIPHERAL_OFFSET		(0x00004400UL)
#define USART2_PERIPHERAL				(APB1_PERIPHERAL + USART2_PERIPHERAL)

#define LPUART1_PERIPHERAL_OFFSET		(0X00004800)
#define	LPUART1_PERIPHERAL				(APB1_PERIPHERAL + LPUART1_PERIPHERAL_OFFSET)

//SECTION APB2
#define APB2_PERIPHERAL_OFFSET			(0x00010000UL)
#define APB2_PERIPHERAL					(PERIPHERAL_BASE + APB2_PERIPHERAL_OFFSET)

#define ADC1_PERIPHERAL_OFFSET			(0x00002400UL)
#define ADC1_PERIPHERAL					(APB2_PERIPHERAL + ADC1_PERIPHERAL_OFFSET)

#define SPI1_PERIPHERAL_OFFSET			(0x00003000UL)
#define SPI1_PERIPHERA					(APB2_PERIPHERAL + SPI1_PERIPHERAL_OFFSET)


//SECTION AHB
#define AHB_PERIPHERAL_OFFSET			(0x00020000UL)
#define AHB_PERIPHERAL					(PERIPHERAL_BASE + AHB_PERIPHERAL_OFFSET)

#define RCC_PERIPHERAL_OFFSET			(0X00001000)
#define RCC_PERIPHERAL					(AHB_PERIPHERAL + RCC_PERIPHERAL_OFFSET)

//SECTION IOPORT
#define IOPORT_PERIPHERAL_OFFSET		(0x10000000UL)
#define IOPORT_PERIPHERAL				(PERIPHERAL_BASE + IOPORT_PERIPHERAL_OFFSET)

#define GPIOA_PERIPHERAL_OFFSET			(0x0000UL)
#define	GPIOA_PERIPHERAL				(GPIOA_PERIPHERAL_OFFSET + IOPORT_PERIPHERAL)

#define	GPIOB_PERIPHERAL_OFFSET			(0x00000400UL)
#define GPIOB_PERIPHERAL				(GPIOB_PERIPHERAL_OFFSET + IOPORT_PERIPHERAL)

#define GPIOC_PERIPHERAL_OFFSET			(0x00000800UL)
#define GPIOC_PERIPHERAL				(GPIOC_PERIPHERAL_OFFSET + IOPORT_PERIPHERAL)


enum State {
    OFF = 48,   //int 48 ascii 0
    ON = 49     //int 49 ascii 1
};





#endif /* INC_BASE_H_ */
